#!/usr/bin/env python3

"""
A script that allows to keep Ansible Vault passwords in a gpg encrypted files
managed by pass (https://www.passwordstore.org) or compatible password managers
like gopass (https://www.gopass.pw).

Password store lookup priority:
  1. --vault-id CLI option
  2. ANSIBLE_VAULT_PASSWORDSTORE environment variable
  3. [vault] passwordstore in ansible.cfg
"""

import shlex
import sys
from argparse import ArgumentParser as AP
from configparser import ConfigParser
from os import environ, getcwd, path
from subprocess import run

# Password manager command (pass, gopass, 'gopass show -o', etc.)
pass_command = shlex.split(
    environ.get('ANSIBLE_VAULT_PASS_COMMAND', '')) or ['pass']

# Get Ansible config file
try:
    import ansible.constants as C
    ansible_config_file = C.CONFIG_FILE
except ImportError:
    try:
        ansible_config_file = environ['ANSIBLE_CONFIG']
    except KeyError:
        cfg = getcwd() + '/' + 'ansible.cfg'
        if path.isfile(cfg):
            ansible_config_file = cfg
        else:
            ansible_config_file = path.expanduser('~/.ansible.cfg')


def get_vault_id():
    # Get passwordstore name from '--vault-id' CLI option
    parser = AP(description='Get a vault password from passwordstore',
                epilog='Please read the README.md file for more info.',
                allow_abbrev=False)

    parser.add_argument('--vault-id', action='store', default='default',
                        dest='vault_id',
                        help='passwordstore containing the vault password')

    vault_id = parser.parse_args().vault_id.strip()

    # Ansible always invokes client scripts with '--vault-id <label>' and
    # uses the literal label 'default' when no label was given, so 'default'
    # means "not specified" and enables the env/config fallback below.
    return '' if vault_id == 'default' else vault_id


def get_config_passwordstore():
    # Get passwordstore name from Ansible config file
    config = ConfigParser()
    config.read(ansible_config_file)
    return config.get('vault', 'passwordstore', fallback='').strip()


def get_env_passwordstore():
    # Get passwordstore name from environment variable
    return environ.get('ANSIBLE_VAULT_PASSWORDSTORE', '').strip()


def main():
    passwordstore = get_vault_id()
    if not passwordstore:
        passwordstore = get_env_passwordstore()
    if not passwordstore:
        passwordstore = get_config_passwordstore()

    if not passwordstore:
        sys.stderr.write(
            "Couldn't get passwordstore settings from --vault-id option, "
            "ANSIBLE_VAULT_PASSWORDSTORE env variable, or Ansible config "
            "file!\nPlease read the README.md "
            "file for more info about script settings.\n")
        sys.exit(1)

    # Get vault password from passwordstore
    try:
        proc = run(pass_command + [passwordstore],
                   capture_output=True, text=True)
    except FileNotFoundError:
        sys.stderr.write("Password manager command '%s' not found in PATH!\n"
                         % pass_command[0])
        sys.exit(1)

    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        sys.exit(proc.returncode)

    sys.stdout.write(proc.stdout.split("\n")[0])
    sys.exit(0)


if __name__ == "__main__":
    main()
